### PR TITLE
Allow to add all packages of a maintainer

### PR DESCRIPTION
**Pull request by dword-design**
This PR adds an input field to add all packages of a maintainer to the graph, since you are usually concerned about your maintaining packages.

### CODE REVIEW

**Comment by dword-design** [comment]
@spoenemann it's done!

**Comment by dword-design** [comment]
@spoenemann Hey, when are you planning to deploy the last PRs?

**Comment by spoenemann** [comment]
Thanks for the reminder! I'll trigger a deployment soon.

**Comment by spoenemann** [comment]
@dword-design done.

**Comment by meysholdt** [comment]
@dword-design thank you for your contributions! Awesome work! :-D

**Comment by dword-design** [comment]
@spoenemann @meysholdt Thanks all =)

**Pull request merged**
